const EXAMPLES: Record<string, string> = {
  es: 'agua',
  en: 'water',
  uk: 'вода',
  de: 'Wasser',
  fr: 'eau',
  it: 'acqua',
  pt: 'água',
  pl: 'woda',
  nl: 'water',
  ru: 'вода',
  ja: '水',
  zh: '水',
  ko: '물',
  ar: 'ماء',
  tr: 'su',
  sv: 'vatten',
  da: 'vand',
  no: 'vann',
  fi: 'vesi',
  cs: 'voda',
  sk: 'voda',
  hu: 'víz',
  ro: 'apă',
  bg: 'вода',
  hr: 'voda',
  he: 'מים',
  hi: 'पानी',
  id: 'air',
  vi: 'nước',
  th: 'น้ำ',
  af: 'water',
  sq: 'ujë',
  hy: 'ջուր',
  ka: 'წყალი',
  ms: 'air',
  sw: 'maji',
  tl: 'tubig',
  el: 'νερό',
  lt: 'vanduo',
  lv: 'ūdens',
  et: 'vesi',
  sr: 'вода',
  mk: 'вода',
  sl: 'voda',
  be: 'вада',
  mn: 'ус',
  az: 'su',
  kk: 'су',
  uz: 'suv',
  am: 'ውሃ',
  so: 'biyo',
  ha: 'ruwa',
  yo: 'omi',
  ig: 'mmiri',
  zu: 'amanzi',
  xh: 'amanzi',
}

export function getLanguageExample(code: string): string | null {
  return EXAMPLES[code] ?? null
}
