addons:
  code_climate:
    repo_token: 82995aa9ad9deef4427585bcafd193e1329a03a7913860d9f5d03d401a2b1117
language: ruby
sudo: required
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: IB6WtkaJ4tVFau62dxdwTRKVritBrf3Ez1D3cOFVmZA7HraB1tG+z6ZmgnJ774DOG74ZpI0vyjBS4ukXvbhVgS2BglUWHaGQo/WP3jMex8AKZzXorV8TOYbVNb2c+tLwt6slKrnL8b9gtfoFd7DwtO3xv920uOvwZhF/E7cOcc/qI0Z43m3T8wwPv6zirPvJU4/MecmJGio90tk/3aAGH55IKWG8ir+3bL7uTJfgmqzgwm9kBfpF1AZDpDX2sGafFt9aQ2Yc4t+3QZCScTJbwOt61+idA2WjTFLJug8negKZZM4K/p87lS5hm+NXiLErBNWO6al/5RlczGDeRvsko1NfEbIWiUpbplyGE2dHnPLmM/0qkVkYgxG8UbrfX+ho2xXp/SNltwQi3pzCb1oMok9Aaqo4LKLuy6177xHfsQBQNtDClNoITpzaSeuwMnsNmtPAU/jS9sIE1osW22pZniVdyXnOWbHKaPDwLTZUUtKHFAPzbantHqGP4iO5Hsy+Hr9HCW/PV7N43/ZQhsW5NNcgRKuoPQjA3a0+jsmGTbcOhwndu7qcpwm+zUUY0GkriTxXjyhV8sC3+2SCfyTl/9ujZ2yUCNjBWhkUJaggSENsJLEkK6QLL+tcAeor7cAlpSzo3oRqnmrwnRxTpCWn1V2XPdJqSeIAJv0L+MTXVMc=
