export type LanguageCatalogEntry = {
  code: string;
  englishName: string;
  nativeName: string;
  flag: string;
  popularSortOrder: number | null;
};

/**
 * Curated study language catalog for EPIC-24.
 * Source list provided by product owner (107 languages).
 */
export const LANGUAGE_CATALOG: LanguageCatalogEntry[] = [
  {
    code: 'af',
    englishName: 'Afrikaans',
    nativeName: 'Afrikaans',
    flag: '🇿🇦',
    popularSortOrder: null,
  },
  {
    code: 'sq',
    englishName: 'Albanian',
    nativeName: 'Shqip',
    flag: '🇦🇱',
    popularSortOrder: null,
  },
  {
    code: 'am',
    englishName: 'Amharic',
    nativeName: 'አማርኛ',
    flag: '🇪🇹',
    popularSortOrder: null,
  },
  {
    code: 'ar',
    englishName: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    popularSortOrder: null,
  },
  {
    code: 'hy',
    englishName: 'Armenian',
    nativeName: 'Հայերեն',
    flag: '🇦🇲',
    popularSortOrder: null,
  },
  {
    code: 'az',
    englishName: 'Azerbaijani',
    nativeName: 'Azərbaycan',
    flag: '🇦🇿',
    popularSortOrder: null,
  },
  {
    code: 'eu',
    englishName: 'Basque',
    nativeName: 'Euskara',
    flag: '🇪🇸',
    popularSortOrder: null,
  },
  {
    code: 'be',
    englishName: 'Belarusian',
    nativeName: 'Беларуская',
    flag: '🇧🇾',
    popularSortOrder: null,
  },
  {
    code: 'bn',
    englishName: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇧🇩',
    popularSortOrder: null,
  },
  {
    code: 'bs',
    englishName: 'Bosnian',
    nativeName: 'Bosanski',
    flag: '🇧🇦',
    popularSortOrder: null,
  },
  {
    code: 'bg',
    englishName: 'Bulgarian',
    nativeName: 'Български',
    flag: '🇧🇬',
    popularSortOrder: null,
  },
  {
    code: 'ca',
    englishName: 'Catalan',
    nativeName: 'Català',
    flag: '🇪🇸',
    popularSortOrder: null,
  },
  {
    code: 'ceb',
    englishName: 'Cebuano',
    nativeName: 'Cebuano',
    flag: '🇵🇭',
    popularSortOrder: null,
  },
  {
    code: 'ny',
    englishName: 'Chichewa',
    nativeName: 'Chichewa',
    flag: '🇲🇼',
    popularSortOrder: null,
  },
  {
    code: 'zh-Hans',
    englishName: 'Chinese (Simplified)',
    nativeName: '简体中文',
    flag: '🇨🇳',
    popularSortOrder: null,
  },
  {
    code: 'co',
    englishName: 'Corsican',
    nativeName: 'Corsu',
    flag: '🇫🇷',
    popularSortOrder: null,
  },
  {
    code: 'hr',
    englishName: 'Croatian',
    nativeName: 'Hrvatski',
    flag: '🇭🇷',
    popularSortOrder: null,
  },
  {
    code: 'cs',
    englishName: 'Czech',
    nativeName: 'Čeština',
    flag: '🇨🇿',
    popularSortOrder: null,
  },
  {
    code: 'da',
    englishName: 'Danish',
    nativeName: 'Dansk',
    flag: '🇩🇰',
    popularSortOrder: null,
  },
  {
    code: 'nl',
    englishName: 'Dutch',
    nativeName: 'Nederlands',
    flag: '🇳🇱',
    popularSortOrder: null,
  },
  {
    code: 'en',
    englishName: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    popularSortOrder: 1,
  },
  {
    code: 'eo',
    englishName: 'Esperanto',
    nativeName: 'Esperanto',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'et',
    englishName: 'Estonian',
    nativeName: 'Eesti',
    flag: '🇪🇪',
    popularSortOrder: null,
  },
  {
    code: 'fil',
    englishName: 'Filipino',
    nativeName: 'Filipino',
    flag: '🇵🇭',
    popularSortOrder: null,
  },
  {
    code: 'fi',
    englishName: 'Finnish',
    nativeName: 'Suomi',
    flag: '🇫🇮',
    popularSortOrder: null,
  },
  {
    code: 'fr',
    englishName: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    popularSortOrder: 3,
  },
  {
    code: 'fy',
    englishName: 'Frisian',
    nativeName: 'Frysk',
    flag: '🇳🇱',
    popularSortOrder: null,
  },
  {
    code: 'gl',
    englishName: 'Galician',
    nativeName: 'Galego',
    flag: '🇪🇸',
    popularSortOrder: null,
  },
  {
    code: 'ka',
    englishName: 'Georgian',
    nativeName: 'ქართული',
    flag: '🇬🇪',
    popularSortOrder: null,
  },
  {
    code: 'de',
    englishName: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    popularSortOrder: 4,
  },
  {
    code: 'el',
    englishName: 'Greek',
    nativeName: 'Ελληνικά',
    flag: '🇬🇷',
    popularSortOrder: null,
  },
  {
    code: 'gu',
    englishName: 'Gujarati',
    nativeName: 'ગુજરાતી',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'ht',
    englishName: 'Haitian Creole',
    nativeName: 'Kreyòl ayisyen',
    flag: '🇭🇹',
    popularSortOrder: null,
  },
  {
    code: 'ha',
    englishName: 'Hausa',
    nativeName: 'Hausa',
    flag: '🇳🇬',
    popularSortOrder: null,
  },
  {
    code: 'haw',
    englishName: 'Hawaiian',
    nativeName: 'ʻŌlelo Hawaiʻi',
    flag: '🇺🇸',
    popularSortOrder: null,
  },
  {
    code: 'he',
    englishName: 'Hebrew',
    nativeName: 'עברית',
    flag: '🇮🇱',
    popularSortOrder: null,
  },
  {
    code: 'hi',
    englishName: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'hmn',
    englishName: 'Hmong',
    nativeName: 'Hmoob',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'hu',
    englishName: 'Hungarian',
    nativeName: 'Magyar',
    flag: '🇭🇺',
    popularSortOrder: null,
  },
  {
    code: 'is',
    englishName: 'Icelandic',
    nativeName: 'Íslenska',
    flag: '🇮🇸',
    popularSortOrder: null,
  },
  {
    code: 'ig',
    englishName: 'Igbo',
    nativeName: 'Igbo',
    flag: '🇳🇬',
    popularSortOrder: null,
  },
  {
    code: 'id',
    englishName: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    flag: '🇮🇩',
    popularSortOrder: null,
  },
  {
    code: 'ga',
    englishName: 'Irish Gaelic',
    nativeName: 'Gaeilge',
    flag: '🇮🇪',
    popularSortOrder: null,
  },
  {
    code: 'it',
    englishName: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    popularSortOrder: 6,
  },
  {
    code: 'ja',
    englishName: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    popularSortOrder: null,
  },
  {
    code: 'jv',
    englishName: 'Javanese',
    nativeName: 'Basa Jawa',
    flag: '🇮🇩',
    popularSortOrder: null,
  },
  {
    code: 'kn',
    englishName: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'kk',
    englishName: 'Kazakh',
    nativeName: 'Қазақ',
    flag: '🇰🇿',
    popularSortOrder: null,
  },
  {
    code: 'km',
    englishName: 'Khmer',
    nativeName: 'ខ្មែរ',
    flag: '🇰🇭',
    popularSortOrder: null,
  },
  {
    code: 'rw',
    englishName: 'Kinyarwanda',
    nativeName: 'Ikinyarwanda',
    flag: '🇷🇼',
    popularSortOrder: null,
  },
  {
    code: 'ko',
    englishName: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    popularSortOrder: null,
  },
  {
    code: 'ku',
    englishName: 'Kurdish (Kurmanji)',
    nativeName: 'Kurdî',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'ky',
    englishName: 'Kyrgyz',
    nativeName: 'Кыргызча',
    flag: '🇰🇬',
    popularSortOrder: null,
  },
  {
    code: 'lo',
    englishName: 'Lao',
    nativeName: 'ລາວ',
    flag: '🇱🇦',
    popularSortOrder: null,
  },
  {
    code: 'la',
    englishName: 'Latin',
    nativeName: 'Latina',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'lv',
    englishName: 'Latvian',
    nativeName: 'Latviešu',
    flag: '🇱🇻',
    popularSortOrder: null,
  },
  {
    code: 'lt',
    englishName: 'Lithuanian',
    nativeName: 'Lietuvių',
    flag: '🇱🇹',
    popularSortOrder: null,
  },
  {
    code: 'lb',
    englishName: 'Luxembourgish',
    nativeName: 'Lëtzebuergesch',
    flag: '🇱🇺',
    popularSortOrder: null,
  },
  {
    code: 'mk',
    englishName: 'Macedonian',
    nativeName: 'Македонски',
    flag: '🇲🇰',
    popularSortOrder: null,
  },
  {
    code: 'mg',
    englishName: 'Malagasy',
    nativeName: 'Malagasy',
    flag: '🇲🇬',
    popularSortOrder: null,
  },
  {
    code: 'ms',
    englishName: 'Malay',
    nativeName: 'Bahasa Melayu',
    flag: '🇲🇾',
    popularSortOrder: null,
  },
  {
    code: 'ml',
    englishName: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'mt',
    englishName: 'Maltese',
    nativeName: 'Malti',
    flag: '🇲🇹',
    popularSortOrder: null,
  },
  {
    code: 'mi',
    englishName: 'Maori',
    nativeName: 'Te Reo Māori',
    flag: '🇳🇿',
    popularSortOrder: null,
  },
  {
    code: 'mr',
    englishName: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'mn',
    englishName: 'Mongolian',
    nativeName: 'Монгол',
    flag: '🇲🇳',
    popularSortOrder: null,
  },
  {
    code: 'my',
    englishName: 'Myanmar (Burmese)',
    nativeName: 'မြန်မာ',
    flag: '🇲🇲',
    popularSortOrder: null,
  },
  {
    code: 'ne',
    englishName: 'Nepali',
    nativeName: 'नेपाली',
    flag: '🇳🇵',
    popularSortOrder: null,
  },
  {
    code: 'no',
    englishName: 'Norwegian',
    nativeName: 'Norsk',
    flag: '🇳🇴',
    popularSortOrder: null,
  },
  {
    code: 'or',
    englishName: 'Odia (Oriya)',
    nativeName: 'ଓଡ଼ିଆ',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'ps',
    englishName: 'Pashto',
    nativeName: 'پښتو',
    flag: '🇦🇫',
    popularSortOrder: null,
  },
  {
    code: 'fa',
    englishName: 'Persian',
    nativeName: 'فارسی',
    flag: '🇮🇷',
    popularSortOrder: null,
  },
  {
    code: 'pl',
    englishName: 'Polish',
    nativeName: 'Polski',
    flag: '🇵🇱',
    popularSortOrder: null,
  },
  {
    code: 'pt',
    englishName: 'Portuguese',
    nativeName: 'Português',
    flag: '🇵🇹',
    popularSortOrder: 5,
  },
  {
    code: 'pa',
    englishName: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'ro',
    englishName: 'Romanian',
    nativeName: 'Română',
    flag: '🇷🇴',
    popularSortOrder: null,
  },
  {
    code: 'ru',
    englishName: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    popularSortOrder: null,
  },
  {
    code: 'sm',
    englishName: 'Samoan',
    nativeName: 'Gagana Samoa',
    flag: '🇼🇸',
    popularSortOrder: null,
  },
  {
    code: 'gd',
    englishName: 'Scots Gaelic',
    nativeName: 'Gàidhlig',
    flag: '🇬🇧',
    popularSortOrder: null,
  },
  {
    code: 'sr',
    englishName: 'Serbian',
    nativeName: 'Српски',
    flag: '🇷🇸',
    popularSortOrder: null,
  },
  {
    code: 'st',
    englishName: 'Sesotho',
    nativeName: 'Sesotho',
    flag: '🇱🇸',
    popularSortOrder: null,
  },
  {
    code: 'sn',
    englishName: 'Shona',
    nativeName: 'ChiShona',
    flag: '🇿🇼',
    popularSortOrder: null,
  },
  {
    code: 'sd',
    englishName: 'Sindhi',
    nativeName: 'سنڌي',
    flag: '🇵🇰',
    popularSortOrder: null,
  },
  {
    code: 'si',
    englishName: 'Sinhala',
    nativeName: 'සිංහල',
    flag: '🇱🇰',
    popularSortOrder: null,
  },
  {
    code: 'sk',
    englishName: 'Slovak',
    nativeName: 'Slovenčina',
    flag: '🇸🇰',
    popularSortOrder: null,
  },
  {
    code: 'sl',
    englishName: 'Slovenian',
    nativeName: 'Slovenščina',
    flag: '🇸🇮',
    popularSortOrder: null,
  },
  {
    code: 'so',
    englishName: 'Somali',
    nativeName: 'Soomaali',
    flag: '🇸🇴',
    popularSortOrder: null,
  },
  {
    code: 'es',
    englishName: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    popularSortOrder: 2,
  },
  {
    code: 'su',
    englishName: 'Sundanese',
    nativeName: 'Basa Sunda',
    flag: '🇮🇩',
    popularSortOrder: null,
  },
  {
    code: 'sw',
    englishName: 'Swahili',
    nativeName: 'Kiswahili',
    flag: '🇰🇪',
    popularSortOrder: null,
  },
  {
    code: 'sv',
    englishName: 'Swedish',
    nativeName: 'Svenska',
    flag: '🇸🇪',
    popularSortOrder: null,
  },
  {
    code: 'tg',
    englishName: 'Tajik',
    nativeName: 'Тоҷикӣ',
    flag: '🇹🇯',
    popularSortOrder: null,
  },
  {
    code: 'ta',
    englishName: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'tt',
    englishName: 'Tatar',
    nativeName: 'Татар',
    flag: '🇷🇺',
    popularSortOrder: null,
  },
  {
    code: 'te',
    englishName: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    popularSortOrder: null,
  },
  {
    code: 'th',
    englishName: 'Thai',
    nativeName: 'ไทย',
    flag: '🇹🇭',
    popularSortOrder: null,
  },
  {
    code: 'tr',
    englishName: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    popularSortOrder: null,
  },
  {
    code: 'tk',
    englishName: 'Turkmen',
    nativeName: 'Türkmen',
    flag: '🇹🇲',
    popularSortOrder: null,
  },
  {
    code: 'uk',
    englishName: 'Ukrainian',
    nativeName: 'Українська',
    flag: '🇺🇦',
    popularSortOrder: null,
  },
  {
    code: 'ur',
    englishName: 'Urdu',
    nativeName: 'اردو',
    flag: '🇵🇰',
    popularSortOrder: null,
  },
  {
    code: 'ug',
    englishName: 'Uyghur',
    nativeName: 'ئۇيغۇرچە',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'uz',
    englishName: 'Uzbek',
    nativeName: 'Oʻzbek',
    flag: '🇺🇿',
    popularSortOrder: null,
  },
  {
    code: 'vi',
    englishName: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    popularSortOrder: null,
  },
  {
    code: 'cy',
    englishName: 'Welsh',
    nativeName: 'Cymraeg',
    flag: '🇬🇧',
    popularSortOrder: null,
  },
  {
    code: 'xh',
    englishName: 'Xhosa',
    nativeName: 'isiXhosa',
    flag: '🇿🇦',
    popularSortOrder: null,
  },
  {
    code: 'yi',
    englishName: 'Yiddish',
    nativeName: 'ייִדיש',
    flag: '🌐',
    popularSortOrder: null,
  },
  {
    code: 'yo',
    englishName: 'Yoruba',
    nativeName: 'Yorùbá',
    flag: '🇳🇬',
    popularSortOrder: null,
  },
  {
    code: 'zu',
    englishName: 'Zulu',
    nativeName: 'isiZulu',
    flag: '🇿🇦',
    popularSortOrder: null,
  },
];

export const LANGUAGE_CATALOG_BY_CODE = new Map(
  LANGUAGE_CATALOG.map((entry) => [entry.code, entry]),
);
