# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80c74cdcabf0fd559f42b693cd76e53d149f038f047108d1a3e1b292f93d2790402f69f0bc8c8a116acfe2e9f4155f29886ae99773c1a462fda4ff4062f9d61
  sorcery_vk_key: "5291391"
  sorcery_vk_secret: "gdhtCausQjY3cXznunhL"
  sorcery_vk_callback_url: "http://localhost:3000/oauth/callback?provider=vk"
  sorcery_facebook_key: "786936561411934"
  sorcery_facebook_secret: "7b3ec9305eb36c2ca8417462b80b2032"
  sorcery_facebook_callback_url: "http://localhost:3000/oauth/callback?provider=facebook"

test:
  secret_key_base: 77146f144707e841b8bd358b3fe9b4949042061e9a240682658f1cee5250eaf989cbc2083702ef341ba6a6b8c99cf5a4e3c2b44ae49fe4a991d94b10363e3225


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
