export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  USER_BLOCKED: 'USER_BLOCKED',

  DECK_NOT_FOUND: 'DECK_NOT_FOUND',
  DECK_FORBIDDEN: 'DECK_FORBIDDEN',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_FORBIDDEN: 'CARD_FORBIDDEN',

  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_NOT_ACTIVE: 'LESSON_NOT_ACTIVE',
  LESSON_CARD_ALREADY_REVIEWED: 'LESSON_CARD_ALREADY_REVIEWED',
  INVALID_REVIEW_ANSWER: 'INVALID_REVIEW_ANSWER',

  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_FORBIDDEN: 'GROUP_FORBIDDEN',
  GROUP_INVITATION_NOT_FOUND: 'GROUP_INVITATION_NOT_FOUND',
  GROUP_INVITATION_INVALID: 'GROUP_INVITATION_INVALID',

  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
